# Copyright contributors to the ai-on-z-triton-is-examples project.
name: snapenvz
channels:
  - defaults
dependencies:
  - python=3.10
  - git
  - pip
  - scikit-learn=1.1.3
  - pandas=1.4.2
  - scipy=1.10.0
  - numpy=1.22.3
  - pip:
    - sklearn2pmml==0.90.4
    - snapml==1.12.0
