# Copyright contributors to the ai-on-z-triton-is-examples project.
name: image_classification
channels:
  - defaults
dependencies:
  - python=3.10
  - git
  - pip
  - scikit-learn=1.1.3
  - pandas=1.5.3
  - scipy=1.9.1
  - numpy=1.23.2
  - matplotlib=3.7.1
  - tensorflow=2.7.0
  - keras=2.7.0
  - seaborn=0.12.2
  - pip:
    - pillow==9.4.0
    - opencv-python==4.7.0.72
